import React from "react";
import logo from "../../logo.svg";
import "./App2.css";

function App() {
  return (
    <div className="App">
      <div>
        GOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYEGOODDBYE
      </div>
    </div>
  );
}

export default App;
